app/core/models.py
from datetime import datetime

from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import current_user
from flask.ext.cache import Cache

db = SQLAlchemy()
cache = Cache()


class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    username = db.Column(db.String(128))
    password = db.Column(db.String(128))
    over = db.Column(db.String(128))
    email = db.Column(db.String(128))
    orders = db.relationship('Order', backref='user')

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def has_unfinished_order(self, parkinglot):
        orders = db.session.query(User).filter_by(id=self.id).order_by('order_time')

    def __unicode__(self):
        return self.username

    @classmethod
    def is_exist(cls, username):
        return User.query.filter_by(username=username).first() != None

    @classmethod
    def get_user_by(cls, username):
        user = User.query.filter_by(username=username).first()
        return user if user else None


class Parkinglot(db.Model):
    __tablename__ = 'parkinglot'

    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128))
    city = db.Column(db.String(128))
    address = db.Column(db.String(128))
    charge = db.Column(db.String(128))

    orders = db.relationship('Order', backref='parkinglot')
    lots = db.relationship('Lot', backref='parkinglot')


class Lot(db.Model):
    __tablename__ = 'lot'

    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    num = db.Column(db.INTEGER)
    status = db.Column(db.SMALLINT)

    p_id = db.Column(db.BIGINT, db.ForeignKey('parkinglot.id'))
    orders = db.relationship('Order', backref='lot')


class Order(db.Model):
    __tablename__ = 'order'
    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    start_time = db.Column(db.DATETIME)
    end_time = db.Column(db.DATETIME)
    order_time = db.Column(db.DATETIME)
    status = db.Column(db.SMALLINT)

    p_id = db.Column(db.BIGINT, db.ForeignKey('parkinglot.id'))
    lot_id = db.Column(db.BIGINT, db.ForeignKey('lot.id'))
    user_id = db.Column(db.BIGINT, db.ForeignKey('user.id'))

app/models.py
from datetime import datetime

from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.cache import Cache

db = SQLAlchemy()
cache = Cache()


class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    username = db.Column(db.String(128))
    password = db.Column(db.String(128))
    over = db.Column(db.String(128))
    email = db.Column(db.String(128))
    orders = db.relationship('Order', backref='user')

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def has_unfinished_order(self, parkinglot):
        orders = db.session.query(User).filter_by(id=self.id).order_by('order_time')

    def __unicode__(self):
        return self.username

    @classmethod
    def is_exist(cls, username):
        return User.query.filter_by(username=username).first() != None

    @classmethod
    def get_user_by(cls, username):
        user = User.query.filter_by(username=username).first()
        return user if user else None


class Parkinglot(db.Model):
    __tablename__ = 'parkinglot'

    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128))
    city = db.Column(db.String(128))
    address = db.Column(db.String(128))
    charge = db.Column(db.String(128))

    orders = db.relationship('Order', backref='parkinglot')
    lots = db.relationship('Lot', backref='parkinglot')



class Lot(db.Model):
    __tablename__ = 'lot'

    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    num = db.Column(db.INTEGER)
    status = db.Column(db.SMALLINT)

    p_id = db.Column(db.BIGINT, db.ForeignKey('parkinglot.id'))
    orders = db.relationship('Order', backref='lot')


class Order(db.Model):
    __tablename__ = 'order'
    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    start_time = db.Column(db.DATETIME)
    end_time = db.Column(db.DATETIME)
    order_time = db.Column(db.DATETIME)
    status = db.Column(db.SMALLINT)

    p_id = db.Column(db.BIGINT, db.ForeignKey('parkinglot.id'))
    lot_id = db.Column(db.BIGINT, db.ForeignKey('lot.id'))
    user_id = db.Column(db.BIGINT, db.ForeignKey('user.id'))


class Manager(db.Model):
    __tablename__ = 'manager'
    id = db.Column(db.BIGINT, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128))
    password = db.Column(db.String(128))

    p_id = db.Column(db.BIGINT, db.ForeignKey('parkinglot.id'))

    def __unicode__(self):
        return self.parkinglot.name + '-' + self.name

app/__init__.py
from flask import Flask

from app.models import db
from app.core.views import main_bp
from app.manager.views import manager_bp
from app.admin.views import admin
import flask_wtf
import config


def create_app():
    app = Flask(__name__)
    app.config.from_object(config.Config)
    register_database(app)
    register_blueprint(app)
    register_admin(app)
    flask_wtf.CsrfProtect(app)
    return app


def register_database(app):
    db.init_app(app)
    db.app = app


def register_blueprint(app):
    app.register_blueprint(main_bp)
    app.register_blueprint(manager_bp)


def register_admin(app):
    admin.init_app(app)

app/admin/__init__.py
# encoding=utf-8
__author__ = 'raidyue'

app/admin/views.py
# encoding=utf-8
__author__ = 'raidyue'
from flask_admin.contrib.sqla import ModelView
from flask_admin.base import BaseView, expose
from flask_admin import Admin
from ..models import db, User, Parkinglot

admin = Admin(name='parkinglot', template_mode='bootstrap3')


class MyView(BaseView):
    @expose('/')
    def index(self):
        return self.render('admin/index.html')


admin.add_view(MyView(name='MyView'))
# admin.add_view(ModelView(User, db.session))
# admin.add_view(ModelView(Parkinglot, db.session))

app/core/views.py
# encoding=utf-8
from flask import Blueprint, render_template, request, session, url_for, redirect, flash

from app.models import User, db

main_bp = Blueprint('main', __name__)


@main_bp.route('/hello')
def hello():
    return render_template('helloworld.html')


@main_bp.route('/')
def index():
    username = session.get('username', None)
    return render_template('index.html', username=username)


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    print 'method=%s' % request.method
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        print username, password
        user = db.session.query(User).filter_by(username=username).first()
        if user:
            session['username'] = user.username
            return redirect(url_for('.index'))
        else:
            flash(u'该用户不存在')
            return render_template('login.html')
    else:
        return url_for('.index')


@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    elif request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if not User.is_exist(username):
            u = User(username=username, password=password)
            db.session.add(u)
            db.session.commit()
            session['username'] = username
            return redirect(url_for('.index'))
        else:
            flash(u'该用户已存在')
            return render_template('register.html')
    else:
        return url_for('.index')


@main_bp.route('/logout')
def logout():
    if 'username' in session:
        session.pop('username')
    return redirect(url_for('.index'))


@main_bp.route('/add/<name>/<passwd>')
def create_user(name, passwd):
    u = User(username=name, password=passwd)
    db.session.add(u)
    db.session.commit()
    return 'success'

app/manager/__init__.py
__author__ = 'raidyue'

app/manager/views.py
# encoding=utf-8
__author__ = 'raidyue'
from flask import Blueprint, render_template, session, request
from ..models import *

manager_bp = Blueprint('manager', __name__, url_prefix='/manager', template_folder='templates')


@manager_bp.route('/')
def index():
    if 'manager' in session:
        return 'login manager'

    return render_template('htllo.html')


@manager_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['name']
        password = request.form['password']
        return render_template('')
    elif request.method == 'GET':
        return render_template('manager_login.html')

app/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}" type="text/css"/>

    <!-- 可选的Bootstrap主题文件（一般不用引入） -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap-theme.min.css') }}" type="text/css"/>

    <link href="{{ url_for('static',filename='css/signin.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/navbar.css') }}" rel="stylesheet">

</head>
<body>
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">&nbsp;趣 停&nbsp;</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% block nav %}
                    <li class="active"><a href="#">主页</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                {% endblock %}
                <!--
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
                -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% block right_bar %}
                    ...
                {% endblock %}
            </ul>
        </div>
        <!--/.nav-collapse -->
        </ul>
    </div>
</nav>

<div class="container">
    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="panel panel-default">
            <div class="panel-body">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
<!-- /container -->

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>

<script src="{{ url_for('static',filename='js/ie-emulation-modes-warning.js') }}"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

app/templates/error_info.html
{% extends 'parkinglot/base.html' %}
{% block nav %}
    <li class="active"><a href="{% url 'index' %}">主页</a></li>
    <li><a href="{% url 'user_order' 1 %}">我的</a></li>
    <li><a href="#contact">Contact</a></li>
{% endblock %}
{% block right-bar %}
    {% if user %}
        <li><a href="#">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}">登出</a></li>
    {% else %}
        <li><a href="{% url 'login' %}">登录</a></li>
        <li><a href="{% url 'register' %}">注册</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    {% if error_info %}
        <div class="alert alert-danger " role="alert">
            <strong>预定失败!</strong>{{ error_info }}
        </div>
        <div class="container text-center">
            <a href="{% url 'index' %}" type="button" class="btn btn-primary btn-sm">返回</a>
        </div>
    {% endif %}
{% endblock %}

app/templates/helloworld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>Hello World!</p>
<input type="text" />
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block nav %}
    <li class="active"><a href="#">主页</a></li>
    <li><a href="#">我的订单</a></li>
    <li><a href="#contact">Contact</a></li>
{% endblock %}
{% block right_bar %}
    {% if username %}
        <li><a href="#">{{ username }}</a></li>
        <li><a href="{{ url_for('main.logout') }}">登出</a></li>
    {% else %}
        <li><a href="{{ url_for('main.login') }}">登录</a></li>
        <li><a href="{{ url_for('main.register') }}">注册</a></li>
    {% endif %}
{% endblock %}

{% block content %}
<!--{#    {% if parkinglots %}#}-->
        <table class="table table-hover table-condensed">
            <thead>
            <tr>
                <th>停车场</th>
                <th>城市</th>
                <th>地址</th>
                <th>价格(/h)</th>
            </tr>
            </thead>
            <tbody>
<!--{#            {% for parkinglot in parkinglots %}#}-->
<!--{#                <tr>#}-->
<!--{#                    <th>{{ parkinglot.name }}</th>#}-->
<!--{#                    <th>{{ parkinglot.city }}</th>#}-->
<!--{#                    <th>{{ parkinglot.address }}</th>#}-->
<!--{#                    <th>{{ parkinglot.charge }}</th>#}-->
<!--{#                    <th>#}-->
<!--{#                        {% if user %}#}-->
<!--{#                            {% if user.over >= parkinglot.charge %}#}-->
<!--{#                                <form action="{% url 'order_lot' %}" method="post">#}-->
<!--{#                                    {% csrf_token %}#}-->
<!--{#                                    <input type="text" hidden="hidden" value="{{ parkinglot.id }}"#}-->
<!--{#                                           name="parkinglot_id"/>#}-->
<!--{#                                    <input type="text" hidden="hidden" value="{{ user.username }}" name="username"/>#}-->
<!--{#                                    {% if not parkinglot.is_full %}#}-->
<!--{#                                        <button class="btn btn-primary btn-xs" type="submit">预定</button>#}-->
<!--{#                                    {% else %}#}-->
<!--{#                                        <button type="button" class=" btn btn-warning btn-xs">已满</button>#}-->
<!--{#                                    {% endif %}#}-->
<!--{#                                </form>#}-->
<!--{#                            {% else %}#}-->
<!--{#                                <button type="button" class=" btn btn-danger btn-xs">请充值</button>#}-->
<!--{#                            {% endif %}#}-->
<!--{#                        {% else %}#}-->
<!--{#                            <a type="button" class=" btn btn-info btn-xs" href="{% url 'login' %}">请登录</a>#}-->
<!--{#                        {% endif %}#}-->
<!--{#                    </th>#}-->
<!--{#                </tr>#}-->
{#            {% endfor %}#}
            </tbody>
        </table>
<!--{#    {% endif %}#}-->
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block nav %}
    <li class="active"><a href="{{ url_for('main.index') }}">主页</a></li>
    <li><a href="#">我的</a></li>
    <li><a href="#contact">Contact</a></li>
{% endblock %}
{% block right_bar %}
    <li><a href="{{ url_for('main.login') }}">登录</a></li>
    <li><a href="{{ url_for('main.register') }}">注册</a></li>
{% endblock %}
{% block content %}

    <div class="container">

        <form class="form-signin" action="{{ url_for('main.login') }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <h2 class="form-signin-heading">请登录</h2>
            <label for="inputUsername" class="sr-only">用户名</label>
            <input type="text" id="inputUsername" class="form-control" placeholder="用户名" name="username" required
                   autofocus>
            <label for="inputPassword" class="sr-only">密码</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="password" required>

            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me" name="remember_me">记住我
                </label>
            </div>

            {% with messages=get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        </form>

    </div>
    <!-- /container -->
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% block nav %}
<li class="active"><a href="{{ url_for('main.index') }}">主页</a></li>
<li><a href="#">我的</a></li>
<li><a href="#contact">Contact</a></li>
{% endblock %}
{% block right_bar %}
<li><a href="{{ url_for('main.logout') }}">登录</a></li>
<li><a href="{{ url_for('main.register') }}">注册</a></li>
{% endblock %}
{% block content %}

<form class="form-signin" action="{{ url_for('main.register') }}" method="post">
    <h2 class="form-signin-heading">注册</h2>
    <label for="inputEmail" class="sr-only">邮箱地址</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="邮箱地址" name="email" required autofocus>
    <label for="inputUsername" class="sr-only">用户名</label>
    <input type="text" id="inputUsername" class="form-control" placeholder="用户名" name="username" required
           autofocus>
    <label for="inputPassword" class="sr-only">密码</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="password" required>
    <input type="password" id="repeatPassword" class="form-control" placeholder="重复密码" name="repeatPassword"
           required>
    {% with messages=get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <button class="btn btn-lg btn-primary btn-block" type="submit">确认</button>
</form>

<!-- /container -->
{% endblock %}

app/templates/user_info.html
{% extends 'parkinglot/base.html' %}
{% block nav %}
    <li><a href="{% url 'index' %}">主页</a></li>
    <li><a href="{% url 'user_order' 1 %}">我的订单</a></li>
    <li><a href="#contact">Contact</a></li>
{% endblock %}

{% block right-bar %}
    {% if user %}
        <li class="active"><a href="{% url 'user_info' %}">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}">登出</a></li>
    {% else %}
        <li><a href="{% url 'login' %}">登录</a></li>
        <li><a href="{% url 'register' %}">注册</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    {% if user %}
        <form class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label">用户名</label>

                <div class="col-sm-10">
                    <label class="form-control-static">{{ user.username }}</label>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">余额</label>

                <div class="col-sm-10">
                    <label class="form-control-static">{{ user.over }}</label>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">邮件</label>

                <div class="col-sm-10">
                    <label class="form-control-static">{{ user.email }}</label>
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}

app/templates/user_order.html
{% extends 'parkinglot/base.html' %}
{% load parkinglot_tags %}
{% block nav %}
    <li><a href="{% url 'index' %}">主页</a></li>
    <li class="active"><a href="{% url 'user_order' 1 %}">我的订单</a></li>
    <li><a href="#contact">Contact</a></li>
{% endblock %}

{% block right-bar %}
    {% if user %}
        <li><a href="{% url 'user_info' %}">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}">登出</a></li>
    {% else %}
        <li><a href="{% url 'login' %}">登录</a></li>
        <li><a href="{% url 'register' %}">注册</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-body">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>订单号</th>
                    <th>停车场</th>
                    <th>车位</th>
                    <th>下单时间</th>
                    <th>开始时间</th>
                    <th>结束时间</th>
                    <th>价格</th>
                </tr>
                </thead>
                <tbody>
                {% if orders %}
                    {% for order in orders %}
                        <tr>
                            <th>{{ order.id }}</th>
                            <th>{{ order.parkinglot.name }}</th>
                            <th>{{ order.lot.num }}</th>
                            <th>{{ order.order_time|date:"Y-m-d H:i" }}</th>
                            <th>{{ order.start_time|date:"Y-m-d H:i"|default:"0000-00-00 00:00" }}</th>
                            <th>{{ order.end_time|date:"Y-m-d H:i"|default:"0000-00-00 00:00" }}</th>
                            <th>20.0</th>
                            <th>
                                {% if order.status == 0 %}
                                    <label class="text-danger">已预定</label>
                                {% elif order.status == 1 %}
                                    <form action="{% url 'order_lot' %}" method="post">
                                        {% csrf_token %}
                                        <input type="text" hidden="hidden" value="{{ parkinglot.id }}"
                                               name="parkinglot_id"/>
                                        <button type="button" class=" btn btn-warning btn-xs">离开</button>
                                    </form>
                                {% elif order.status == 2 %}
                                    <label class="text-success">已完成</label>
                                {% elif order.status == 4 %}
                                    <label class="text-muted">订单失效</label>
                                {% endif %}
                            </th>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
            <nav class="text-center">
                <ul class="pagination">
                    {% if page_id > 1 %}
                        <li>
                            <a href="{% url 'user_order' page_id|add:-1 %}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for count in page_count|page_range %}
                        {% if page_id == count %}
                            <li class="active"><a href="{% url 'user_order' count %}">{{ count }}</a></li>
                        {% else %}
                            <li><a href="{% url 'user_order' count %}">{{ count }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_id < page_count %}
                        <li>
                            <a href="{% url 'user_order' page_id|add:1 %}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}